/**
* Tarnished Messenger
* Open API documents for tarnished messenger written in kotlin
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.du.minigames.app.dto


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param tarnishedUid 
 * @param messageUid 
 * @param rating 
 */

data class AppraiseMessageRequest (
    @field:JsonProperty("tarnished_uid")
    var tarnishedUid: String? = null,
    @field:JsonProperty("message_uid")
    var messageUid: String? = null,
    @field:JsonProperty("rating")
    var rating: String? = null
)

