/**
* Tarnished Messenger
* Open API documents for tarnished messenger written in kotlin
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.du.minigames.app.dto


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param uid 
 * @param tarnishedUid 
 * @param message 
 * @param goodRating 
 * @param badRating 
 */

data class MessageResponse (
    @field:JsonProperty("uid")
    var uid: String? = null,
    @field:JsonProperty("tarnished_uid")
    var tarnishedUid: String? = null,
    @field:JsonProperty("message")
    var message: String? = null,
    @field:JsonProperty("good_rating")
    var goodRating: Int? = null,
    @field:JsonProperty("bad_rating")
    var badRating: Int? = null
)

