/**
* Tarnished Messenger
* Open API documents for tarnished messenger written in kotlin
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.du.minigames.app.dto


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param tarnishedUid 
 * @param subject 
 * @param subjectTemplate 
 */

data class SendMessageRequest (
    @field:JsonProperty("tarnished_uid")
    var tarnishedUid: String? = null,
    @field:JsonProperty("subject")
    var subject: String? = null,
    @field:JsonProperty("subject_template")
    var subjectTemplate: Int? = null
)

