/**
* Tarnished Messenger
* Open API documents for tarnished messenger written in kotlin
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.du.minigames.app.dto


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param uid 
 * @param username 
 * @param status 
 */

data class TarnishedResponse (
    @field:JsonProperty("uid")
    var uid: String? = null,
    @field:JsonProperty("username")
    var username: String? = null,
    @field:JsonProperty("status")
    var status: String? = null
)

